### PR TITLE
Fixed #98 check subquery counts when creating alias

### LINKED ISSUE #98: When nesting several queries, aliases are reused
The query is:

```sql
SELECT COALESCE(SUM("sq0"."expected"),0) "expected"
FROM (
    (
        SELECT SUM("sq0"."view_count") FROM (
            SELECT MIN("user_queries"."view_count")
            FROM "user_queries"
            JOIN (
                SELECT "user_query_word"."user_query_id","user_query_word"."language"
                FROM "words" JOIN "user_query_word" USING ("word_id")
                WHERE "words"."word"='best'
            ) "sq0" USING ("user_query_id")
            JOIN (
                SELECT "user_query_word"."user_query_id","user_query_word"."language" 
                FROM "words" 
                JOIN "user_query_word" USING ("word_id")
                WHERE "words"."word"='mortgage'
            ) "sq1" USING ("user_query_id")
            WHERE "user_queries"."user_query"<>'bestmortgage' AND "sq0"."language"="sq1"."language" 
            GROUP BY "user_queries"."user_query_id"
        ) "sq0"
    ) UNION ALL (
        SELECT "view_count"*1.0 "expected" FROM "user_queries" WHERE "user_query"='bestmortgage'
    )
) "sq0"
```

And the error:

```
psycopg2.ProgrammingError: column sq0.view_count does not exist
LINE 1: ..."sq0"."expected"),0) "expected" FROM ((SELECT SUM("sq0"."vie...
```

### PR DESCRIPTION
**Pull request by tobymao**

### CODE REVIEW

**Comment by tobymao** [comment]
hm, just noticed this doesn't work for another nesting level.

**Comment by tobymao** [comment]
that should hopefully do it

**Comment by twheys** [comment]
@tobymao I really appreciate you fixing this! It's been on my plate for a while now but haven't had time to look at it.

**Comment by twheys** [comment]
Published in 0.14.3

**Pull request merged**
