### PR TITLE
Enclose CASE statement in parentheses

### PR DESCRIPTION
**Pull request by cpinamtz**
Just as a dumb idea to deal with this problem that other users have already mentioned (#508). In my case, I need this for the `CASE` statement.

### CODE REVIEW

**Comment by gl3nn** [comment]
I don't think this relates to the linked issue (as there it seems to be related to order of operations) but if this is needed for certain platforms then we can merge it in. What platform are you targeting?

**Comment by cpinamtz** [comment]
Well it's true it's not totally related but there is a problem trying to use parentheses depending of the needs of your query. 

I'm working with Oracle

**Comment by cpinamtz** [comment]
For those who need to enclose your `CASE` statements when you're using them in **arithmetical expression** like the following:
```sql 
(CASE WHEN cond1 THEN then1 ELSE else1 END) + 
(CASE WHEN cond2 THEN then2 ELSE else2 END) + 
(CASE WHEN cond3 THEN then3 ELSE else3 END) + 
...
```
You can really enclose between parenthesis your `CASE` statements with the following workaround:
```python
your_sum += 1 * (0 + Case().when(cond, sta1).else_(sta22))
```
To understand why, check [the `ArithmeticExpression`'s `get_sql` method](https://github.com/kayak/pypika/blob/3c33b639350cbaa1c7cfba04aeab5ef8c590d1b0/pypika/terms.py#L980-L984) 

Anyways, I'm not going to close this issue 'cause I don't know if there is someone has a trickier situation where this workaround is not feasible. Up to you :ok_hand:

**Comment by gl3nn** [comment]
I looked up some Oracle documentation and it doesn't seem like parentheses are needed at all : https://docs.oracle.com/cd/B19306_01/server.102/b14200/expressions004.htm . I believe the test you added in the PR would also work without parentheses for Oracle. Are you using the case statement in an arithmetical expression? (That wasn't clear before but would explain the link with the ticket.) If that's the case then I don't think this PR makes sense and then it should be solved on the arithmetic level.

**Pull request closed without merging**
