### PR TITLE
Inserting and updating data support key-value pairs

### PR DESCRIPTION
**Pull request by Zhiwei1996**
Hello, firend

`pypika` is awesome, thanks for your creation

In many cases, inserting and updating data use dict directly is convenient, and then I add features for it

What do you think?

### CODE REVIEW

**Comment by stephane-klein** [comment]
@Zhiwei1996 @mikeengland some news about this Pull Request ?

**Comment by gl3nn** [comment]
While I like the general idea, I'm not a big fan of the implementation. Especially the insert needs a different API.

The set_many I could be convinced by, if it reused the implementation of many.

@stephane-klein What do you need from this PR?

**Comment by Zhiwei1996** [comment]
> While I like the general idea, I'm not a big fan of the implementation. Especially the insert needs a different API.
> 
> 
> 
> The set_many I could be convinced by, if it reused the implementation of many.
> 
> 
> 
> @stephane-klein What do you need from this PR?

I also think the implementation is not elegant，but the idea is useful
Can you implement it, or give some suggestions, I will reimplement

**Comment by gl3nn** [comment]
Did you remove your commit? Github has incorrectly marked this as merged.

**Pull request merged**
