### PR TITLE
fix some types when downstream enabled this package in mypy

### PR DESCRIPTION
**Pull request by trim21**
mypy raise some error when I add py.typed file manually (https://github.com/kayak/pypika/pull/666)

details:

add `pypika.__all__`

fix select command, `def select(self, *terms: Sequence[Union[int, float, str, bool, Term, Field]]) -> "QueryBuilder":` to `def select(self, *terms: Union[int, float, str, bool, Term, Field]) -> "QueryBuilder":`

add common types to subclass of `DistinctOptionFunction`

### CODE REVIEW

**Comment by AzisK** [comment]
Does it make sense to add tests about it?

**Comment by trim21** [comment]
not really for this PR

**Comment by AzisK** [comment]
It looks good to me. Thanks for the work. Merging

**Review by AzisK — APPROVED** [review]

**Comment by AzisK** [comment]
Should I simply revert this or would you have some improvements regarding it?

I am not really a mypy user, therefore not my expertise

**Comment by trim21** [comment]
Sorry, I don't use pypika anymore, you can consider revert it.

**Pull request merged**
