### PR TITLE
fix(terms): fixed EmptyCriterion bug with ComplexCriterion

### PR DESCRIPTION
**Pull request by GeorgiySurkov**
issue: https://github.com/kayak/pypika/issues/327

### CODE REVIEW

**Review by AzisK — APPROVED** [review]
Good job and thanks for working on this

**Comment by AzisK** [comment]
For some reason the CI tests did not run with this PR. Could you update the code with the newest from the master branch?

**Comment by GeorgiySurkov** [comment]
Yes, of course!

**Comment by AzisK** [comment]
It looks good and I am merging this but version bump will come later

**Pull request merged**
